export interface IntMoviePage {
    cast:{
        character:string,
        name:string,
        profile_path:string
    }[],
    details:{
        budget:number,
        categories:{
            id:number,
            name:string,
        }[],
        homepage:string,
        lang:string,
        overview:string,
        picture:string,
        popularity:number,
        poster:string,
        production:{
            id:number,
            logo_path:string,
            name:string,
            origin_country:string,
        }[],
        profit:number,
        release:string,
        title:string,
        vote:number
    },
    reviews:{
        author_details:{
            name:string,
            username:string,
            avatar_path:string,
        },
        content:string,
        created_at:string,
    }[],
    trailers:{
        name:string,
        key:string,
        site:string,
    }[]
}